# Generated by Django 6.0.1 on 2026-01-09 20:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('FOLLOW_UP', 'Follow-up')], default='CONSULTATION', max_length=20)),
                ('chief_complaint', models.CharField(blank=True, default='', max_length=255)),
                ('history_of_present_illness', models.TextField(blank=True, default='')),
                ('physical_exam', models.TextField(blank=True, default='')),
                ('assessment', models.TextField(blank=True, default='')),
                ('plan', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heart_rate_bpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate_rpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygen_saturation_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('head_circumference_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='visits.visit')),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
    ]
