# Generated by Django 5.1.4 on 2026-01-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='complementary_exam',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='medical_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='treatment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
