# Generated by Django 5.1.4 on 2026-01-21 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.CharField(choices=[('morning', 'Morning (8:00-12:00)'), ('afternoon', 'Afternoon (12:00-17:00)'), ('evening', 'Evening (17:00-21:00)'), ('full_day', 'Full Day'), ('unavailable', 'Unavailable')], default='full_day', max_length=20)),
                ('start_time', models.TimeField(blank=True, help_text='Custom start time', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Custom end time', null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Availability',
                'verbose_name_plural': 'Doctor Availabilities',
                'ordering': ['date'],
                'unique_together': {('doctor', 'date')},
            },
        ),
    ]
