# Generated by Django 5.1.4 on 2026-01-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_doctor_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='clinic_address',
            field=models.TextField(blank=True, help_text='Clinic/practice address to appear on prescriptions'),
        ),
    ]
