# Generated by Django 6.0.1 on 2026-01-09 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('form', models.CharField(blank=True, default='', max_length=50)),
                ('strength', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'strength', 'form'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='visits.visit')),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_prescriptions', to='prescriptions.prescriptiontemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, default='', max_length=100)),
                ('route', models.CharField(blank=True, default='', max_length=50)),
                ('frequency', models.CharField(blank=True, default='', max_length=50)),
                ('duration', models.CharField(blank=True, default='', max_length=50)),
                ('instructions', models.TextField(blank=True, default='')),
                ('allow_outside_purchase', models.BooleanField(default=False, help_text='Allow patient to buy outside hospital if out of stock.')),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prescriptions.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, default='', max_length=100)),
                ('route', models.CharField(blank=True, default='', max_length=50)),
                ('frequency', models.CharField(blank=True, default='', max_length=50)),
                ('duration', models.CharField(blank=True, default='', max_length=50)),
                ('instructions', models.TextField(blank=True, default='')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescriptions.medication')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescriptiontemplate')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
