# Generated by Django 5.1.4 on 2026-01-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='description_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
