# Generated by Django 6.0.1 on 2026-01-17 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prescriptionitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prescriptiontemplate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prescriptiontemplateitem',
            options={},
        ),
        migrations.AlterField(
            model_name='medication',
            name='form',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='medication',
            name='strength',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='template_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescriptions.prescriptiontemplate'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='allow_outside_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dosage',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='duration',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='frequency',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescriptions.medication'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='route',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='prescriptiontemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescriptiontemplate',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='prescriptiontemplateitem',
            name='dosage',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='prescriptiontemplateitem',
            name='duration',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='prescriptiontemplateitem',
            name='frequency',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='prescriptiontemplateitem',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescriptiontemplateitem',
            name='route',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
