# Generated by Django 5.1.4 on 2026-02-02 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_reminders_enabled'),
        ('patients', '0006_add_patient_file_model'),
        ('visits', '0002_add_medical_history_complementary_exam_treatment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='E.164 phone number sent to', max_length=30)),
                ('provider', models.CharField(default='africastalking', max_length=30)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10)),
                ('message_id', models.CharField(blank=True, default='', help_text='Provider message ID for delivery tracking', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No-show'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['reminders_enabled', 'reminder_sent_at', 'scheduled_at', 'status'], name='idx_reminder_query'),
        ),
        migrations.AddField(
            model_name='appointmentsmslog',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='appointments.appointment'),
        ),
        migrations.AddIndex(
            model_name='appointmentsmslog',
            index=models.Index(fields=['appointment', 'status'], name='appointment_appoint_0f4406_idx'),
        ),
    ]
