# Generated by Django 5.1.4 on 2026-02-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_reminders_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No-show'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20),
        ),
    ]
