# Generated by Django 5.1.4 on 2026-01-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_add_patient_file_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
